
spring:
  datasource:
    url: jdbc:mysql://10.50.40.145:3306/adasdb_v4?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: cdwk-3g-145
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml