
spring:
  datasource:
    url: jdbc:mysql://10.50.40.145:3306/${DATABASE}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml